"""Generate TFT thresholds and web help from the API's single rule source."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
rules = json.loads((root / 'api/indoor_rules.json').read_text(encoding='utf-8'))
header = ['// Generated by tools/generate_indoor_rules.py; edit api/indoor_rules.json.',
          '#pragma once', 'namespace IndoorRules {',
          f'constexpr unsigned READ_INTERVAL_MS = {rules["readIntervalMs"]};',
          f'constexpr unsigned STALE_AFTER_MS = {rules["staleAfterMs"]};']
for metric in ('temperature', 'humidity'):
    header.append(f'inline const char *{metric}Status(float value) {{')
    for rule in rules[metric]:
        label = json.dumps(rule['label'], ensure_ascii=False)
        if rule['upper'] is None:
            header.append(f'  return {label};')
        else:
            op = '<=' if rule['inclusive'] else '<'
            header.append(f'  if (value {op} {rule["upper"]}.0f) return {label};')
    header.append('}')
header.append('}')
(root / 'esp32/src/indoor_rules.h').write_text('\n'.join(header) + '\n', encoding='utf-8')
(root / 'frontend/indoor-rules.js').write_text(
    '// Generated from api/indoor_rules.json.\nconst indoorRules = ' +
    json.dumps(rules, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print('Generated TFT rules and web help from indoor_rules.json')
